import { ScriptLanguageOption } from '../../types';

export const FEATURED_LANGUAGES = [
  'en', 'hi', 'gu', 'mr', 'pa', 'bn', 'ta', 'te', 'kn', 'ml', 'ur', 'ar', 'ja', 'zh', 'ko', 'ru', 'fr', 'de', 'es'
];

export const SUPPORTED_LANGUAGES: ScriptLanguageOption[] = [
  {
    code: 'auto',
    name: 'Auto Detect',
    nativeName: 'Auto Detect',
    script: 'Latin',
    defaultFont: 'Plus Jakarta Sans',
    fontOptions: [
      { name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" },
      { name: 'Inter', family: "'Inter', sans-serif" },
    ],
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    defaultFont: 'Plus Jakarta Sans',
    fontOptions: [
      { name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" },
      { name: 'Playfair Display', family: "'Playfair Display', serif" },
      { name: 'Montserrat', family: "'Montserrat', sans-serif" },
      { name: 'Cinzel', family: "'Cinzel', serif" },
      { name: 'Bebas Neue', family: "'Bebas Neue', cursive" },
    ],
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    defaultFont: 'Noto Sans Devanagari',
    fontOptions: [
      { name: 'Noto Sans Devanagari', family: "'Noto Sans Devanagari', sans-serif" },
      { name: 'Mukta', family: "'Mukta', sans-serif" },
      { name: 'Hind', family: "'Hind', sans-serif" },
      { name: 'Rozha One', family: "'Rozha One', serif" },
      { name: 'Kalam', family: "'Kalam', cursive" },
      { name: 'Tillana', family: "'Tillana', cursive" },
    ],
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati',
    defaultFont: 'Noto Sans Gujarati',
    fontOptions: [
      { name: 'Noto Sans Gujarati', family: "'Noto Sans Gujarati', sans-serif" },
      { name: 'Hind Vadodara', family: "'Hind Vadodara', sans-serif" },
      { name: 'Baloo Bhai 2', family: "'Baloo Bhai 2', cursive" },
      { name: 'Shrikhand', family: "'Shrikhand', cursive" },
      { name: 'Rasa', family: "'Rasa', serif" },
      { name: 'Mogra', family: "'Mogra', cursive" },
    ],
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari',
    defaultFont: 'Mukta',
    fontOptions: [
      { name: 'Mukta', family: "'Mukta', sans-serif" },
      { name: 'Hind', family: "'Hind', sans-serif" },
      { name: 'Noto Sans Devanagari', family: "'Noto Sans Devanagari', sans-serif" },
      { name: 'Kalam', family: "'Kalam', cursive" },
    ],
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    defaultFont: 'Noto Sans Gurmukhi',
    fontOptions: [
      { name: 'Noto Sans Gurmukhi', family: "'Noto Sans Gurmukhi', sans-serif" },
      { name: 'Mukta Mahee', family: "'Mukta Mahee', sans-serif" },
      { name: 'Baloo Paaji 2', family: "'Baloo Paaji 2', cursive" },
    ],
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali',
    defaultFont: 'Noto Sans Bengali',
    fontOptions: [
      { name: 'Noto Sans Bengali', family: "'Noto Sans Bengali', sans-serif" },
      { name: 'Hind Siliguri', family: "'Hind Siliguri', sans-serif" },
      { name: 'Galada', family: "'Galada', cursive" },
      { name: 'Atma', family: "'Atma', cursive" },
      { name: 'Mina', family: "'Mina', sans-serif" },
    ],
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    defaultFont: 'Noto Sans Tamil',
    fontOptions: [
      { name: 'Noto Sans Tamil', family: "'Noto Sans Tamil', sans-serif" },
      { name: 'Arima', family: "'Arima', cursive" },
      { name: 'Mukta Malar', family: "'Mukta Malar', sans-serif" },
      { name: 'Catamaran', family: "'Catamaran', sans-serif" },
      { name: 'Pavanam', family: "'Pavanam', sans-serif" },
    ],
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu',
    defaultFont: 'Noto Sans Telugu',
    fontOptions: [
      { name: 'Noto Sans Telugu', family: "'Noto Sans Telugu', sans-serif" },
      { name: 'Gurajada', family: "'Gurajada', serif" },
      { name: 'Ramabhadra', family: "'Ramabhadra', sans-serif" },
      { name: 'Peddana', family: "'Peddana', serif" },
      { name: 'Suranna', family: "'Suranna', serif" },
    ],
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada',
    defaultFont: 'Noto Sans Kannada',
    fontOptions: [
      { name: 'Noto Sans Kannada', family: "'Noto Sans Kannada', sans-serif" },
      { name: 'Noto Serif Kannada', family: "'Noto Serif Kannada', serif" },
      { name: 'Hubballi', family: "'Hubballi', cursive" },
    ],
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam',
    defaultFont: 'Noto Sans Malayalam',
    fontOptions: [
      { name: 'Noto Sans Malayalam', family: "'Noto Sans Malayalam', sans-serif" },
      { name: 'Chilanka', family: "'Chilanka', cursive" },
      { name: 'Manjari', family: "'Manjari', sans-serif" },
      { name: 'Gayathri', family: "'Gayathri', sans-serif" },
    ],
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'Arabic/Perso-Arabic',
    defaultFont: 'Noto Nastaliq Urdu',
    fontOptions: [
      { name: 'Noto Nastaliq Urdu', family: "'Noto Nastaliq Urdu', serif" },
      { name: 'Noto Sans Arabic', family: "'Noto Sans Arabic', sans-serif" },
      { name: 'Gulzar', family: "'Gulzar', serif" },
      { name: 'Amiri', family: "'Amiri', serif" },
    ],
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    script: 'Arabic',
    defaultFont: 'Noto Sans Arabic',
    fontOptions: [
      { name: 'Noto Sans Arabic', family: "'Noto Sans Arabic', sans-serif" },
      { name: 'Amiri', family: "'Amiri', serif" },
      { name: 'Cairo', family: "'Cairo', sans-serif" },
      { name: 'El Messiri', family: "'El Messiri', sans-serif" },
      { name: 'Aref Ruqaa', family: "'Aref Ruqaa', serif" },
    ],
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    script: 'Kanji/Hiragana/Katakana',
    defaultFont: 'Noto Sans JP',
    fontOptions: [
      { name: 'Noto Sans JP', family: "'Noto Sans JP', sans-serif" },
      { name: 'Zen Kaku Gothic New', family: "'Zen Kaku Gothic New', sans-serif" },
      { name: 'Kaisei Tokumin', family: "'Kaisei Tokumin', serif" },
      { name: 'Shippori Mincho', family: "'Shippori Mincho', serif" },
      { name: 'Potta One', family: "'Potta One', cursive" },
    ],
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    nativeName: '中文 (简体)',
    script: 'Hanzi',
    defaultFont: 'Noto Sans SC',
    fontOptions: [
      { name: 'Noto Sans SC', family: "'Noto Sans SC', sans-serif" },
      { name: 'ZCOOL XiaoWei', family: "'ZCOOL XiaoWei', serif" },
      { name: 'ZCOOL QingKe HuangYou', family: "'ZCOOL QingKe HuangYou', cursive" },
      { name: 'Ma Shan Zheng', family: "'Ma Shan Zheng', cursive" },
    ],
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    script: 'Hangul',
    defaultFont: 'Noto Sans KR',
    fontOptions: [
      { name: 'Noto Sans KR', family: "'Noto Sans KR', sans-serif" },
      { name: 'Black Han Sans', family: "'Black Han Sans', sans-serif" },
      { name: 'Do Hyeon', family: "'Do Hyeon', sans-serif" },
      { name: 'Gowun Batang', family: "'Gowun Batang', serif" },
    ],
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    script: 'Cyrillic',
    defaultFont: 'Montserrat',
    fontOptions: [
      { name: 'Montserrat', family: "'Montserrat', sans-serif" },
      { name: 'Oswald', family: "'Oswald', sans-serif" },
      { name: 'Playfair Display', family: "'Playfair Display', serif" },
      { name: 'Roboto', family: "'Roboto', sans-serif" },
    ],
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    script: 'Latin',
    defaultFont: 'Plus Jakarta Sans',
    fontOptions: [
      { name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" },
      { name: 'Playfair Display', family: "'Playfair Display', serif" },
      { name: 'Cinzel', family: "'Cinzel', serif" },
    ],
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    script: 'Latin',
    defaultFont: 'Plus Jakarta Sans',
    fontOptions: [
      { name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" },
      { name: 'Oswald', family: "'Oswald', sans-serif" },
      { name: 'Cinzel', family: "'Cinzel', serif" },
    ],
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    script: 'Latin',
    defaultFont: 'Plus Jakarta Sans',
    fontOptions: [
      { name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" },
      { name: 'Montserrat', family: "'Montserrat', sans-serif" },
      { name: 'Playfair Display', family: "'Playfair Display', serif" },
    ],
  },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', script: 'Ethiopic', defaultFont: 'Noto Sans Ethiopic', fontOptions: [{ name: 'Noto Sans Ethiopic', family: "'Noto Sans Ethiopic', sans-serif" }] },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', script: 'Armenian', defaultFont: 'Noto Sans Armenian', fontOptions: [{ name: 'Noto Sans Armenian', family: "'Noto Sans Armenian', sans-serif" }] },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', script: 'Georgian', defaultFont: 'Noto Sans Georgian', fontOptions: [{ name: 'Noto Sans Georgian', family: "'Noto Sans Georgian', sans-serif" }] },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', script: 'Greek', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', script: 'Hebrew', defaultFont: 'Noto Sans Hebrew', fontOptions: [{ name: 'Noto Sans Hebrew', family: "'Noto Sans Hebrew', sans-serif" }, { name: 'Heebo', family: "'Heebo', sans-serif" }] },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', script: 'Khmer', defaultFont: 'Noto Sans Khmer', fontOptions: [{ name: 'Noto Sans Khmer', family: "'Noto Sans Khmer', sans-serif" }] },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ', script: 'Lao', defaultFont: 'Noto Sans Lao', fontOptions: [{ name: 'Noto Sans Lao', family: "'Noto Sans Lao', sans-serif" }] },
  { code: 'la', name: 'Latin', nativeName: 'Latina', script: 'Latin', defaultFont: 'Cinzel', fontOptions: [{ name: 'Cinzel', family: "'Cinzel', serif" }] },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', script: 'Devanagari', defaultFont: 'Mukta', fontOptions: [{ name: 'Mukta', family: "'Mukta', sans-serif" }] },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'fa', name: 'Persian (Farsi)', nativeName: 'فارسی', script: 'Arabic', defaultFont: 'Vazirmatn', fontOptions: [{ name: 'Vazirmatn', family: "'Vazirmatn', sans-serif" }, { name: 'Amiri', family: "'Amiri', serif" }] },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', script: 'Sinhala', defaultFont: 'Noto Sans Sinhala', fontOptions: [{ name: 'Noto Sans Sinhala', family: "'Noto Sans Sinhala', sans-serif" }] },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', script: 'Thai', defaultFont: 'Prompt', fontOptions: [{ name: 'Prompt', family: "'Prompt', sans-serif" }, { name: 'Mitr', family: "'Mitr', sans-serif" }] },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', script: 'Cyrillic', defaultFont: 'Montserrat', fontOptions: [{ name: 'Montserrat', family: "'Montserrat', sans-serif" }] },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', script: 'Hebrew', defaultFont: 'Noto Sans Hebrew', fontOptions: [{ name: 'Noto Sans Hebrew', family: "'Noto Sans Hebrew', sans-serif" }] },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', script: 'Latin', defaultFont: 'Plus Jakarta Sans', fontOptions: [{ name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif" }] },
];

export function loadGoogleFontForScript(fontName: string) {
  if (!fontName) return;
  const linkId = `google-font-${fontName.replace(/\s+/g, '-').toLowerCase()}`;
  if (document.getElementById(linkId)) return;

  const fontQuery = fontName.replace(/\s+/g, '+');
  const link = document.createElement('link');
  link.id = linkId;
  link.rel = 'stylesheet';
  link.href = `https://fonts.googleapis.com/css2?family=${fontQuery}:wght@400;500;600;700;800;900&display=swap`;
  document.head.appendChild(link);
}
