import { GoogleFont, FontCategory, PairingStyle, TypographyPairing, FontRole, TypographyRoleConfig } from '../types';

// Set of loaded fonts to prevent redundant link tags
const loadedFontLinks = new Set<string>();

/**
 * Dynamically injects a Google Font <link> into document <head>
 */
export function loadGoogleFont(family: string, weights: number[] = [300, 400, 500, 600, 700, 800, 900]): void {
  if (!family || typeof document === 'undefined') return;

  const fontKey = `${family}:${weights.join(',')}`;
  if (loadedFontLinks.has(fontKey)) return;

  try {
    const formattedFamily = family.replace(/\s+/g, '+');
    const weightsParam = weights.join(';');
    const fontUrl = `https://fonts.googleapis.com/css2?family=${formattedFamily}:ital,wght@0,${weightsParam};1,${weightsParam}&display=swap`;

    // Check if link element already exists
    const existingLink = document.querySelector(`link[href="${fontUrl}"]`);
    if (!existingLink) {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = fontUrl;
      document.head.appendChild(link);
    }

    loadedFontLinks.add(fontKey);
  } catch (err) {
    console.warn('Failed to load Google Font dynamically:', family, err);
  }
}

/**
 * Curated Database of Google Fonts across 7 categories
 */
export const POPULAR_GOOGLE_FONTS: GoogleFont[] = [
  // SERIF
  { family: 'Playfair Display', category: 'serif', variants: ['400', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Cinzel', category: 'serif', variants: ['400', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Cormorant Garamond', category: 'serif', variants: ['300', '400', '500', '600', '700'], subsets: ['latin'] },
  { family: 'Merriweather', category: 'serif', variants: ['300', '400', '700', '900'], subsets: ['latin'] },
  { family: 'Lora', category: 'serif', variants: ['400', '500', '600', '700'], subsets: ['latin'] },
  { family: 'Bodoni Moda', category: 'serif', variants: ['400', '600', '700', '900'], subsets: ['latin'] },
  { family: 'PT Serif', category: 'serif', variants: ['400', '700'], subsets: ['latin'] },
  { family: 'Spectral', category: 'serif', variants: ['300', '400', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Prata', category: 'serif', variants: ['400'], subsets: ['latin'] },
  { family: 'DM Serif Display', category: 'serif', variants: ['400'], subsets: ['latin'] },
  { family: 'Libre Baskerville', category: 'serif', variants: ['400', '700'], subsets: ['latin'] },
  { family: 'Vollkorn', category: 'serif', variants: ['400', '600', '700', '900'], subsets: ['latin'] },
  { family: 'Cinzel Decorative', category: 'serif', variants: ['400', '700', '900'], subsets: ['latin'] },
  { family: 'Bitter', category: 'serif', variants: ['300', '400', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Noto Serif', category: 'serif', variants: ['400', '700'], subsets: ['latin'] },
  { family: 'Crimson Pro', category: 'serif', variants: ['300', '400', '600', '700', '800'], subsets: ['latin'] },

  // SANS SERIF
  { family: 'Inter', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Plus Jakarta Sans', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Montserrat', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Poppins', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Outfit', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Roboto', category: 'sans-serif', variants: ['300', '400', '500', '700', '900'], subsets: ['latin'] },
  { family: 'Open Sans', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Lato', category: 'sans-serif', variants: ['300', '400', '700', '900'], subsets: ['latin'] },
  { family: 'Work Sans', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Space Grotesk', category: 'sans-serif', variants: ['300', '400', '500', '600', '700'], subsets: ['latin'] },
  { family: 'Cabinet Grotesk', category: 'sans-serif', variants: ['400', '700', '800', '900'], subsets: ['latin'] },
  { family: 'Sora', category: 'sans-serif', variants: ['300', '400', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Manrope', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Urbanist', category: 'sans-serif', variants: ['300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] },
  { family: 'DM Sans', category: 'sans-serif', variants: ['400', '500', '700'], subsets: ['latin'] },
  { family: 'Lexend', category: 'sans-serif', variants: ['300', '400', '600', '700', '800'], subsets: ['latin'] },

  // DISPLAY
  { family: 'Syne', category: 'display', variants: ['400', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Oswald', category: 'display', variants: ['300', '400', '500', '600', '700'], subsets: ['latin'] },
  { family: 'Bebas Neue', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Clash Display', category: 'display', variants: ['400', '600', '700'], subsets: ['latin'] },
  { family: 'Righteous', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Abril Fatface', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Anton', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Unbounded', category: 'display', variants: ['400', '600', '800', '900'], subsets: ['latin'] },
  { family: 'Monument Extended', category: 'display', variants: ['400', '800'], subsets: ['latin'] },
  { family: 'Russo One', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Chakra Petch', category: 'display', variants: ['400', '600', '700'], subsets: ['latin'] },
  { family: 'Bungee', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Staatliches', category: 'display', variants: ['400'], subsets: ['latin'] },
  { family: 'Ultra', category: 'display', variants: ['400'], subsets: ['latin'] },

  // SCRIPT & HANDWRITING
  { family: 'Great Vibes', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Dancing Script', category: 'script', variants: ['400', '600', '700'], subsets: ['latin'] },
  { family: 'Pacifico', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Alex Brush', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Sacramento', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Satisfy', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Allura', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Parisienne', category: 'script', variants: ['400'], subsets: ['latin'] },
  { family: 'Caveat', category: 'handwriting', variants: ['400', '600', '700'], subsets: ['latin'] },
  { family: 'Shadows Into Light', category: 'handwriting', variants: ['400'], subsets: ['latin'] },
  { family: 'Indie Flower', category: 'handwriting', variants: ['400'], subsets: ['latin'] },
  { family: 'Kalam', category: 'handwriting', variants: ['300', '400', '700'], subsets: ['latin'] },

  // MONOSPACE
  { family: 'JetBrains Mono', category: 'monospace', variants: ['300', '400', '600', '700', '800'], subsets: ['latin'] },
  { family: 'Fira Code', category: 'monospace', variants: ['300', '400', '500', '600', '700'], subsets: ['latin'] },
  { family: 'Space Mono', category: 'monospace', variants: ['400', '700'], subsets: ['latin'] },
  { family: 'Source Code Pro', category: 'monospace', variants: ['300', '400', '600', '700'], subsets: ['latin'] },
  { family: 'Roboto Mono', category: 'monospace', variants: ['300', '400', '600', '700'], subsets: ['latin'] },
  { family: 'Inconsolata', category: 'monospace', variants: ['300', '400', '600', '800'], subsets: ['latin'] },
  { family: 'Share Tech Mono', category: 'monospace', variants: ['400'], subsets: ['latin'] },
];

/**
 * Generate Default Presets for 16 Pairing Styles
 */
export const PRESET_TYPOGRAPHY_PAIRINGS: Record<PairingStyle, TypographyPairing> = {
  luxury: {
    id: 'pair-luxury',
    name: 'Panther Black & Gold Luxury',
    style: 'luxury',
    bgColor: '#0B0B0F',
    roles: {
      heading: {
        fontFamily: 'Cinzel',
        fontWeight: 700,
        fontSize: 48,
        letterSpacing: 3,
        lineHeight: 1.15,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#D4AF37',
        gradient: 'linear-gradient(135deg, #FDE68A 0%, #D4AF37 50%, #9C7A1C 100%)',
      },
      subheading: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 18,
        letterSpacing: 4,
        lineHeight: 1.4,
        wordSpacing: 1,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
      body: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 0.5,
        lineHeight: 1.7,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#BDBDBD',
      },
      caption: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1.5,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#D4AF37',
      },
      button: {
        fontFamily: 'Montserrat',
        fontWeight: 800,
        fontSize: 13,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 13,
        letterSpacing: 1.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  modern: {
    id: 'pair-modern',
    name: 'Modern High Tech',
    style: 'modern',
    bgColor: '#090A0F',
    roles: {
      heading: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 800,
        fontSize: 44,
        letterSpacing: -1,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Inter',
        fontWeight: 600,
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#CBD5E1',
      },
      caption: {
        fontFamily: 'JetBrains Mono',
        fontWeight: 500,
        fontSize: 12,
        letterSpacing: 1,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 700,
        fontSize: 14,
        letterSpacing: 0.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 600,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#F8FAFC',
      },
    },
  },
  minimal: {
    id: 'pair-minimal',
    name: 'Swiss Minimalist',
    style: 'minimal',
    bgColor: '#000000',
    roles: {
      heading: {
        fontFamily: 'Space Grotesk',
        fontWeight: 700,
        fontSize: 42,
        letterSpacing: -1.5,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Space Grotesk',
        fontWeight: 500,
        fontSize: 18,
        letterSpacing: 1,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'DM Sans',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.75,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'DM Sans',
        fontWeight: 400,
        fontSize: 11,
        letterSpacing: 1.5,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.6,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Space Grotesk',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Space Grotesk',
        fontWeight: 500,
        fontSize: 13,
        letterSpacing: 0.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.85,
        color: '#FFFFFF',
      },
    },
  },
  corporate: {
    id: 'pair-corporate',
    name: 'Executive Corporate',
    style: 'corporate',
    bgColor: '#0B0F19',
    roles: {
      heading: {
        fontFamily: 'Merriweather',
        fontWeight: 700,
        fontSize: 38,
        letterSpacing: 0,
        lineHeight: 1.2,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Open Sans',
        fontWeight: 600,
        fontSize: 18,
        letterSpacing: 0.5,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Open Sans',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.65,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Open Sans',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: 1,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.65,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Open Sans',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 0.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Open Sans',
        fontWeight: 600,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  creative: {
    id: 'pair-creative',
    name: 'Avant-Garde Creative',
    style: 'creative',
    bgColor: '#0F0914',
    roles: {
      heading: {
        fontFamily: 'Syne',
        fontWeight: 800,
        fontSize: 52,
        letterSpacing: -1,
        lineHeight: 1.05,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
        gradient: 'linear-gradient(135deg, #FFFFFF 0%, #D4AF37 100%)',
      },
      subheading: {
        fontFamily: 'Cabinet Grotesk',
        fontWeight: 700,
        fontSize: 22,
        letterSpacing: 0,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Syne',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#FACC15',
      },
      button: {
        fontFamily: 'Syne',
        fontWeight: 800,
        fontSize: 14,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Syne',
        fontWeight: 700,
        fontSize: 14,
        letterSpacing: 0.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  editorial: {
    id: 'pair-editorial',
    name: 'Vogue Editorial',
    style: 'editorial',
    bgColor: '#08080A',
    roles: {
      heading: {
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        fontSize: 50,
        letterSpacing: 0,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'italic',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 16,
        letterSpacing: 3,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.85,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Lora',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 0.3,
        lineHeight: 1.75,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 11,
        letterSpacing: 2,
        lineHeight: 1.5,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.6,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Montserrat',
        fontWeight: 700,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  fashion: {
    id: 'pair-fashion',
    name: 'Haute Couture Fashion',
    style: 'fashion',
    bgColor: '#0A0A0C',
    roles: {
      heading: {
        fontFamily: 'Bodoni Moda',
        fontWeight: 700,
        fontSize: 48,
        letterSpacing: 2,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Montserrat',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 4,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Work Sans',
        fontWeight: 300,
        fontSize: 15,
        letterSpacing: 0.5,
        lineHeight: 1.7,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.75,
        color: '#CBD5E1',
      },
      caption: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 11,
        letterSpacing: 2.5,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.6,
        color: '#D4AF37',
      },
      button: {
        fontFamily: 'Bodoni Moda',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 3,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.85,
        color: '#FFFFFF',
      },
    },
  },
  gaming: {
    id: 'pair-gaming',
    name: 'Cyber Gaming & Esports',
    style: 'gaming',
    bgColor: '#06060A',
    roles: {
      heading: {
        fontFamily: 'Unbounded',
        fontWeight: 800,
        fontSize: 44,
        letterSpacing: 0,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FACC15',
        gradient: 'linear-gradient(135deg, #FACC15 0%, #D4AF37 100%)',
      },
      subheading: {
        fontFamily: 'Chakra Petch',
        fontWeight: 700,
        fontSize: 20,
        letterSpacing: 1,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
      body: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Share Tech Mono',
        fontWeight: 400,
        fontSize: 12,
        letterSpacing: 1,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#38BDF8',
      },
      button: {
        fontFamily: 'Unbounded',
        fontWeight: 800,
        fontSize: 13,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Chakra Petch',
        fontWeight: 600,
        fontSize: 14,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  startup: {
    id: 'pair-startup',
    name: 'SaaS & Tech Startup',
    style: 'startup',
    bgColor: '#0A0C14',
    roles: {
      heading: {
        fontFamily: 'Outfit',
        fontWeight: 800,
        fontSize: 46,
        letterSpacing: -1,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Outfit',
        fontWeight: 600,
        fontSize: 20,
        letterSpacing: 0,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#CBD5E1',
      },
      caption: {
        fontFamily: 'JetBrains Mono',
        fontWeight: 500,
        fontSize: 12,
        letterSpacing: 1,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Outfit',
        fontWeight: 700,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Outfit',
        fontWeight: 600,
        fontSize: 14,
        letterSpacing: 0,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  wedding: {
    id: 'pair-wedding',
    name: 'Romantic Wedding',
    style: 'wedding',
    bgColor: '#0C0A0D',
    roles: {
      heading: {
        fontFamily: 'Great Vibes',
        fontWeight: 400,
        fontSize: 56,
        letterSpacing: 1,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#D4AF37',
      },
      subheading: {
        fontFamily: 'Cormorant Garamond',
        fontWeight: 600,
        fontSize: 20,
        letterSpacing: 3,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
      body: {
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fontSize: 17,
        letterSpacing: 0.5,
        lineHeight: 1.7,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'italic',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 11,
        letterSpacing: 2,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#D4AF37',
      },
      button: {
        fontFamily: 'Cormorant Garamond',
        fontWeight: 700,
        fontSize: 14,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Cormorant Garamond',
        fontWeight: 600,
        fontSize: 14,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  vintage: {
    id: 'pair-vintage',
    name: 'Vintage Heritage',
    style: 'vintage',
    bgColor: '#0F0E0A',
    roles: {
      heading: {
        fontFamily: 'Abril Fatface',
        fontWeight: 400,
        fontSize: 48,
        letterSpacing: 1,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#D4AF37',
      },
      subheading: {
        fontFamily: 'Libre Baskerville',
        fontWeight: 700,
        fontSize: 18,
        letterSpacing: 2,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
      body: {
        fontFamily: 'Libre Baskerville',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.7,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#CBD5E1',
      },
      caption: {
        fontFamily: 'Libre Baskerville',
        fontWeight: 400,
        fontSize: 12,
        letterSpacing: 1,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'italic',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Abril Fatface',
        fontWeight: 400,
        fontSize: 14,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Libre Baskerville',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  bold: {
    id: 'pair-bold',
    name: 'Impact Heavy Duty',
    style: 'bold',
    bgColor: '#050505',
    roles: {
      heading: {
        fontFamily: 'Bebas Neue',
        fontWeight: 400,
        fontSize: 58,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Montserrat',
        fontWeight: 800,
        fontSize: 20,
        letterSpacing: 1,
        lineHeight: 1.2,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Montserrat',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Bebas Neue',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 2,
        lineHeight: 1.2,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Bebas Neue',
        fontWeight: 400,
        fontSize: 18,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Montserrat',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  magazine: {
    id: 'pair-magazine',
    name: 'High Life Magazine',
    style: 'magazine',
    bgColor: '#09090C',
    roles: {
      heading: {
        fontFamily: 'DM Serif Display',
        fontWeight: 400,
        fontSize: 48,
        letterSpacing: 0,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Cabinet Grotesk',
        fontWeight: 700,
        fontSize: 18,
        letterSpacing: 1,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.65,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#CBD5E1',
      },
      caption: {
        fontFamily: 'Cabinet Grotesk',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: 1.5,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.65,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Cabinet Grotesk',
        fontWeight: 800,
        fontSize: 13,
        letterSpacing: 1,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Cabinet Grotesk',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 0.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  technology: {
    id: 'pair-tech',
    name: 'Quantum Technology',
    style: 'technology',
    bgColor: '#05070F',
    roles: {
      heading: {
        fontFamily: 'Sora',
        fontWeight: 700,
        fontSize: 44,
        letterSpacing: -1,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Fira Code',
        fontWeight: 500,
        fontSize: 18,
        letterSpacing: 0,
        lineHeight: 1.3,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0,
        lineHeight: 1.6,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Fira Code',
        fontWeight: 400,
        fontSize: 12,
        letterSpacing: 0.5,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.7,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Sora',
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 0.5,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Sora',
        fontWeight: 600,
        fontSize: 13,
        letterSpacing: 0,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  restaurant: {
    id: 'pair-restaurant',
    name: 'Gourmet Bistro',
    style: 'restaurant',
    bgColor: '#0C0908',
    roles: {
      heading: {
        fontFamily: 'Prata',
        fontWeight: 400,
        fontSize: 46,
        letterSpacing: 1,
        lineHeight: 1.15,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#D4AF37',
      },
      subheading: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 16,
        letterSpacing: 3,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.85,
        color: '#FFFFFF',
      },
      body: {
        fontFamily: 'Work Sans',
        fontWeight: 400,
        fontSize: 15,
        letterSpacing: 0.2,
        lineHeight: 1.7,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#CBD5E1',
      },
      caption: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 11,
        letterSpacing: 2,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.65,
        color: '#D4AF37',
      },
      button: {
        fontFamily: 'Prata',
        fontWeight: 400,
        fontSize: 13,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
  elegant: {
    id: 'pair-elegant',
    name: 'Timeless Elegance',
    style: 'elegant',
    bgColor: '#08080C',
    roles: {
      heading: {
        fontFamily: 'Cormorant Garamond',
        fontWeight: 700,
        fontSize: 50,
        letterSpacing: 1,
        lineHeight: 1.1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#FFFFFF',
      },
      subheading: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 17,
        letterSpacing: 3,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#D4AF37',
      },
      body: {
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 400,
        fontSize: 16,
        letterSpacing: 0.3,
        lineHeight: 1.7,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.8,
        color: '#E2E8F0',
      },
      caption: {
        fontFamily: 'Montserrat',
        fontWeight: 500,
        fontSize: 11,
        letterSpacing: 2,
        lineHeight: 1.4,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.6,
        color: '#94A3B8',
      },
      button: {
        fontFamily: 'Cormorant Garamond',
        fontWeight: 700,
        fontSize: 14,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'center',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 1,
        color: '#000000',
      },
      navigation: {
        fontFamily: 'Montserrat',
        fontWeight: 600,
        fontSize: 12,
        letterSpacing: 2,
        lineHeight: 1,
        wordSpacing: 0,
        textAlign: 'left',
        textTransform: 'uppercase',
        fontStyle: 'normal',
        textDecoration: 'none',
        opacity: 0.9,
        color: '#FFFFFF',
      },
    },
  },
};

/**
 * Generate CSS Code for a Typography Pairing
 */
export function generatePairingCSS(pairing: TypographyPairing): string {
  const roles: FontRole[] = ['heading', 'subheading', 'body', 'caption', 'button', 'navigation'];
  let css = `/* Panther Typo Studio - ${pairing.name} (${pairing.style.toUpperCase()}) */\n\n`;

  roles.forEach((role) => {
    const config = pairing.roles[role];
    if (!config) return;
    css += `/* ${role.toUpperCase()} STYLING */\n`;
    css += `.${role}-text {\n`;
    css += `  font-family: '${config.fontFamily}', sans-serif;\n`;
    css += `  font-weight: ${config.fontWeight};\n`;
    css += `  font-size: ${config.fontSize}px;\n`;
    css += `  letter-spacing: ${config.letterSpacing}px;\n`;
    css += `  line-height: ${config.lineHeight};\n`;
    css += `  text-align: ${config.textAlign};\n`;
    if (config.textTransform !== 'none') {
      css += `  text-transform: ${config.textTransform};\n`;
    }
    if (config.fontStyle !== 'normal') {
      css += `  font-style: ${config.fontStyle};\n`;
    }
    if (config.color) {
      css += `  color: ${config.color};\n`;
    }
    css += `}\n\n`;
  });

  return css;
}

/**
 * Generate Google Fonts HTML Link Tag
 */
export function generateGoogleFontsLink(pairing: TypographyPairing): string {
  const families = new Set<string>();

  Object.values(pairing.roles).forEach((role) => {
    if (role.fontFamily) {
      families.add(role.fontFamily);
    }
  });

  const formattedFamilies = Array.from(families)
    .map((f) => `family=${f.replace(/\s+/g, '+')}:wght@300;400;500;600;700;800;900`)
    .join('&');

  return `<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link href="https://fonts.googleapis.com/css2?${formattedFamilies}&display=swap" rel="stylesheet">`;
}

/**
 * Generate Google Fonts CSS @import
 */
export function generateGoogleFontsImport(pairing: TypographyPairing): string {
  const families = new Set<string>();

  Object.values(pairing.roles).forEach((role) => {
    if (role.fontFamily) {
      families.add(role.fontFamily);
    }
  });

  const formattedFamilies = Array.from(families)
    .map((f) => `family=${f.replace(/\s+/g, '+')}:wght@300;400;500;600;700;800;900`)
    .join('&');

  return `@import url('https://fonts.googleapis.com/css2?${formattedFamilies}&display=swap');`;
}

/**
 * Generate Markdown Brand Guide / Specimen Sheet
 */
export function generateTypographyBrandGuide(pairing: TypographyPairing): string {
  let md = `# PANTHER STUDIO - TYPOGRAPHY SPECIMEN GUIDE\n\n`;
  md += `**Style Theme:** ${pairing.name} (${pairing.style.toUpperCase()})\n`;
  md += `**Background Color:** \`${pairing.bgColor}\`\n\n`;
  md += `--- \n\n`;
  md += `## Font Hierarchy & Specifications\n\n`;

  const roles: FontRole[] = ['heading', 'subheading', 'body', 'caption', 'button', 'navigation'];

  roles.forEach((role) => {
    const config = pairing.roles[role];
    md += `### ${role.toUpperCase()}\n`;
    md += `- **Font Family:** ${config.fontFamily}\n`;
    md += `- **Weight:** ${config.fontWeight}\n`;
    md += `- **Size:** ${config.fontSize}px\n`;
    md += `- **Letter Spacing:** ${config.letterSpacing}px\n`;
    md += `- **Line Height:** ${config.lineHeight}\n`;
    md += `- **Color:** \`${config.color}\`\n\n`;
  });

  md += `## Google Fonts Import Link\n\n`;
  md += `\`\`\`html\n${generateGoogleFontsLink(pairing)}\n\`\`\`\n\n`;

  md += `## CSS Rules\n\n`;
  md += `\`\`\`css\n${generatePairingCSS(pairing)}\n\`\`\`\n`;

  return md;
}
